import type { LucideIcon } from 'lucide-react';
import {
  LayoutDashboard,
  Wallet,
  TrendingUp,
  Target,
  Settings,
  Menu,
  Bell,
  User,
  X,
  Building2,
  PiggyBank,
  Eye,
  EyeOff,
  Pencil,
  Trash2,
  Minus,
  Plus,
  Home,
  UtensilsCrossed,
  Car,
  Heart,
  GraduationCap,
  ShoppingCart,
  Receipt,
  Gamepad2,
  Shirt,
  Smartphone,
  Briefcase,
  DollarSign,
  Gift,
  FileText,
  Landmark,
} from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
  // Navegacao
  dashboard: LayoutDashboard,
  lancamentos: Wallet,
  relatorios: TrendingUp,
  metas: Target,
  configuracoes: Settings,
  menu: Menu,
  notificacoes: Bell,
  usuario: User,
  fechar: X,
  // Contas
  'conta-corrente': Building2,
  poupanca: PiggyBank,
  investimento: TrendingUp,
  eye: Eye,
  'eye-off': EyeOff,
  // Acoes
  editar: Pencil,
  excluir: Trash2,
  menos: Minus,
  mais: Plus,
  // Categorias
  moradia: Home,
  alimentacao: UtensilsCrossed,
  transporte: Car,
  saude: Heart,
  educacao: GraduationCap,
  compras: ShoppingCart,
  contas: Receipt,
  lazer: Gamepad2,
  roupas: Shirt,
  assinaturas: Smartphone,
  salario: Briefcase,
  'outras-receitas': DollarSign,
  presentes: Gift,
  rendimentos: Wallet,
  'despesa-padrao': FileText,
  // Alternativas
  bank: Landmark,
};
